debug: false
use_random_seed: true
seed: 461

fold: ???
train_folds: ???
valid_folds: ???

use_wandb: false
all_data: false

add_syn: true
add_pl: true
add_icdar: true

pl_multiplier: 8
extracted_multiplier: 8
icdar_multiplier: 8
original_multiplier: 1

use_augmentations: true

tags:
  - final

model:
  backbone_path: google/matcha-base
  max_length: 512
  max_patches: 4096
  patch_size: 16
  len_tokenizer: ???
  pad_token_id: ???
  decoder_start_token_id: ???
  bos_token_id: ???
  max_length_generation: 8 # 512
  ckpt_path: ../models/r_final/mga_model_fold_0.pth.tar

awp:
  use_awp: false
  awp_trigger: -100
  awp_trigger_epoch: 1
  adv_lr: 5e-5
  adv_eps: 0.001

train_params:
  train_bs: 4
  valid_bs: 4

  num_epochs: 1 # 4
  grad_accumulation: 2
  warmup_pct: 0.05

  save_trigger: -1.0
  use_fp16: true

  eval_frequency: 512 # 1024 # 32000
  patience: 100

  use_ema: true
  decay_rate: 0.9925

optimizer:
  lr: 1e-5
  weight_decay: 1e-5
  grad_clip_value: 1.0

outputs:
  model_dir: ../models/r_rest


fold_metadata:
  n_folds: 2
  fold_dir: ../datasets/processed/fold_split
  fold_path: "cv_map_${fold_metadata.n_folds}_folds.parquet"

competition_dataset:
  data_dir: ../datasets/benetech-making-graphs-accessible
  syn_dir: ../datasets/processed/synthetic
  pl_dir: ../datasets/processed/mga_pl
  icdar_dir: ../datasets/processed/mga_icdar


wandb:
  project: mga-dev-a1
  run_name: rb-exp101-r-rest